spring.application.name=to-do-app

# ---------------- DATABASE (Clever Cloud) ----------------
spring.datasource.url=jdbc:mysql://bc89oy91s6zzslwkc5nm-mysql.services.clever-cloud.com:3306/bc89oy91s6zzslwkc5nm?useSSL=true&requireSSL=true
spring.datasource.username=uutwjquika7ejke3
spring.datasource.password=VSchmfKqJ2oGDtEugNmF
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ---------------- JPA ----------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ---------------- SERVER ----------------
server.port=8080
